### ISSUE TITLE
MED Bargining Unit Issue

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#171] opened 2017-02-24 16:05 UTC
Cant search or add Bun number.... apparently they said this was an issue reported from the ULP section as well.

**Comment by parkjohnston** [comment] 2017-02-24 20:39
Appears to be a duplicate of another ticket..either #165 or #113 

Appears to be working in Beta 11. 

Double clicking the text box.

**Closed by parkjohnston** 2017-02-24 20:39 UTC
Labels: duplicate
