### ISSUE TITLE
(PT050) -- Generate Report button grayed out for 'All' selection

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#239] opened 2017-03-06 15:49 UTC
For the report below, the generate button is greyed out when All is selected, unless user changes investigator name and then selects all again. 

![image](https://cloud.githubusercontent.com/assets/24595073/23617290/a4bcac20-025a-11e7-99e7-0f162d0ead98.png)

Also the report generates blank.
![image](https://cloud.githubusercontent.com/assets/24595073/23617296/a711fdb8-025a-11e7-89b4-70df3f9ec596.png)

**Comment by altrdgenetics** [comment] 2017-03-06 16:36
dropdown issue is duplicate of PT051 that was fixed in issue #240. removing myself from this ticket and only the report issue is left.

**Comment by anthonyperk** [comment] 2017-03-06 17:47
Generate Report button works for All selection.  The report generates with null due to the Investigators dropdown listing SERB investigators and not PBR investigators

**Comment by parkjohnston** [comment] 2017-03-06 23:24
This can be fixed in two seconds, once we get the answer to the question that is holding up several other tickets. 

ALJ == what 
etc

**Comment by altrdgenetics** [comment] 2017-03-07 18:01
So this was not tied to any other tickets. The Dropdown pulled the correct information by the column in the database. This is solely a report issue.

**Comment by altrdgenetics** [comment] 2017-03-08 17:13
Anthony fixed it, he had his parameters all wacked out. Since this is a report it is live now

**Closed by altrdgenetics** 2017-03-08 17:13 UTC
Labels: bug

**Comment by anthonyperk** [comment] 2017-03-08 17:32
I am dumb, please make it known
