### ISSUE TITLE
(PT117)  --  Report Due Date should be 5 months from File Date

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#306] opened 2017-03-11 15:00 UTC
![image](https://cloud.githubusercontent.com/assets/24595073/23824270/6067378a-0641-11e7-9066-2d42cadee891.png)

(From Judy, because she is an angry lady) 3-10-17 – Report due date should be 8/10/17 (5 months from file date) NOT 7/10/17 (4 months) – This issue was also submitted on 2-28-17 – Who changed the calculation to 4 months?

**Comment by anthonyperk** [comment] 2017-03-11 15:01
ULP Section also stated that it should be 150 days from the File Date.  2.0 shows 5 solid months regardless of month or weekends (+5 to the month)

**Comment by parkjohnston** [comment] 2017-03-11 15:02
Duplicate of #304

**Closed by parkjohnston** 2017-03-11 15:02 UTC
Labels: bug
