### ISSUE TITLE
Error when Right Clicking an Activity in CMDS

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#115] opened 2017-02-14 21:43 UTC
CMDS Section -> Activity Tab

When I right clicked on an activity, I got the following error (happens every time):

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.Vector.elementData(Unknown Source)
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at javax.swing.JTable.getValueAt(Unknown Source)
        at parker.serb.activity.ActivityPanel$3.mouseClicked(ActivityPanel.java:98)
        at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)

**Comment by parkjohnston** [comment] 2017-02-15 04:51
please try again with new release, was unable to reproduce, but think it was fixed with another issue that I found based on something else and I have gotten to this last.  Will be leaving this open and awaiting your follow up testing....thanks!

**Comment by parkjohnston** [comment] 2017-02-15 04:51
if not fixed please reopen!

**Comment by anthonyperk** [comment] 2017-02-15 18:30
I was able to recreate.  If there are no rows selected (i.e. coming from a different tab to the activity tab) I got the error again

**Comment by parkjohnston** [comment] 2017-02-15 19:20
found the issue to be right clicking before a row is selected ...

will be requiring a row to first be selected before right clicking

**Closed** 2017-02-15 19:27 UTC
Labels: bug

**Comment by anthonyperk** [comment] 2017-02-17 15:24
Functionality Confirmed
