### ISSUE TITLE
(R3-006) - (ALL) - Ability to highlight and copy information on Case Party Detail Dialog

### ISSUE THREAD

**Issue by altrdgenetics** [CurrentlyNotSet/SERB#573] opened 2017-06-21 14:52 UTC
We would like the ability to be able to copy text from the fields in the Party Information Tab without the need to be in update mode. Some of this information is copied to other documents and outgoing emails.

Is this possible?

![image](https://user-images.githubusercontent.com/8847344/27390624-c04911d6-566f-11e7-85de-7b2dc83834af.png)

**Comment by altrdgenetics** [comment] 2017-06-21 14:53
After R3-005 Allen has stated that any enhancements will be on hold till payment is situated.

**Comment by parkjohnston** [comment] 2017-07-20 22:13
This is another duplicate of #588

**Comment by parkjohnston** [comment] 2017-08-20 23:03
WIP

**Comment by parkjohnston** [comment] 2017-09-01 21:29
closed

Time: 1 hour

**Closed by parkjohnston** 2017-09-01 21:29 UTC
Labels: Enhancement
