### ISSUE TITLE
Search directly for ORG/CSC number

### ISSUE THREAD

**Issue by anthonyperk** [CurrentlyNotSet/SERB#120] opened 2017-02-16 15:00 UTC
ORG and CSC request the functionality to type in an ORG number or CSC number directly without going through the advanced search function.

**Comment by parkjohnston** [comment] 2017-02-16 16:08
this is done....please verify

**Comment by anthonyperk** [comment] 2017-02-16 16:10
confirmed, waiting on andrew to close

**Comment by parkjohnston** [comment] 2017-02-16 16:14
that was something i did...i will close

**Comment by parkjohnston** [comment] 2017-02-16 16:14
Duplicate of #108

**Closed by parkjohnston** 2017-02-16 16:14 UTC
Labels: bug
